Update Tomcat 8.5 to latest patch release 8.5.68 (#227)
* Update Tomcat 8.5 to latest patch release 8.5.68

Sub pom.xml files need to be updated in addition to the top level https://github.com/heroku/webapp-runner/pull/224.

* Fix single_webapp test

The test is sensitive to the output of tomcat. At some point they changed the format of their "starting" string. The case of the "e" in engine changed and they started wrapping "Apache Tomcat" (and version) in square brackets

```
Aug 20, 2021 1:39:00 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service [Tomcat]
Aug 20, 2021 1:39:00 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet engine: [Apache Tomcat/8.5.68]
Aug 20, 2021 1:39:00 PM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Aug 20, 2021 1:39:02 PM org.apache.jasper.servlet.TldScanner scanJars
INFO: At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
. Expression: foundText. Values: foundText = false
```

I also made the error a bit more verbose, adding the expected string, labeling the output, and putting it on a newline:

```
[INFO]   The post-build script did not succeed. ERROR: The web process did not start (filesystem)
Expected output to contain: `Starting Servlet Engine: [Apache Tomcat` but it did not
Output: Adding Context  for /Users/rschneeman/Documents/projects/work/webapp-runner/assembly/target/it/single_webapp/src/main/webapp
Aug 20, 2021 1:39:00 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Aug 20, 2021 1:39:00 PM org.apache.catalina.core.StandardService initInternal
SEVERE: Failed to initialize connector [Connector[HTTP/1.1-8080]]
org.apache.catalina.LifecycleException: Protocol handler initialization failed
```