Create webapps directory in temp dir
This fixes the following error in deployment phase:
SEVERE: Exception fixing docBase for context []
java.io.IOException: Application base [{1}] for host [/app/target/tomcat.5000/webapps] does not exist or is not a directory.